device: cuda
use_wandb: True
num_classes: 1

data:
  class_threshold: 0.6
  num_classes: 1
  mean: [0.485, 0.456, 0.406]
  std:  [0.229, 0.224, 0.225]

train:
  train_dir: data/test/white_bracket
  batch_size: 8

loss:
  loss_types : ["DiceLoss"]
  type: DiceLoss         # dice | iou | gdl | bce | bce_dice

train:
  test_train_split: 0.9
  batch_size: 32
  epochs: 150

optimizer:
  lr: 0.005


