device: cuda
logger_comment: baseline

data:
  class_threshold: 0.6
  num_classes: 1
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  img_size: 640

train:
  train_dir: data/test/white_bracket
  batch_size: 8
  test_train_split: 0.95
  weight_decay: 1e-8
  batch_size: 32
  epochs: 150
  lr: 0.005
  model_save_dir: weights
  save_weights: True

loss:
  loss_types : ["DiceLoss"]
  type: DiceLoss

wandb:
  use_wandb: True
  project: defect_detection


